# Generated by Django 5.0.6 on 2026-08-22 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('work_completed', models.TextField(help_text='What work was completed today?')),
                ('work_in_progress', models.TextField(blank=True, help_text='What is currently in progress?')),
                ('pending_work', models.TextField(blank=True, help_text='What work is pending?')),
                ('blockers', models.TextField(blank=True, help_text='Any blockers or issues?')),
                ('hours_worked', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_updates', to='employees.employeeprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_updates', to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_updates', to='tasks.task')),
            ],
            options={
                'db_table': 'daily_work_update',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('employee', 'date', 'task')},
            },
        ),
    ]
